display_errors = Off
error_reporting = E_ALL & ~E_NOTICE
log_errors = On
error_log = /home/sporte2/logs/php-framadate-error.log
ignore_repeated_errors = On
register_globals = Off
session.cookie_httponly = 1

[Date]
date.timezone = "America/Toronto"
